<footer>
    <div id="social">
        <a href="https://www.facebook.com/tima.prisyazhnyuk" target="_blank" title="Facebook">
            <img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHg9IjBweCIgeT0
            iMHB4IgogICAgIHdpZHRoPSI1MCIgaGVpZ2h0PSI1MCIKICAgICB2aWV3Qm94PSIwIDAgNDggNDgiCiAgICAgc3R5bGU9ImZpbGw6Iz
            AwMDAwMDsiPjxnIGlkPSJzdXJmYWNlMSI+PHBhdGggc3R5bGU9IiBmaWxsOiMzRjUxQjU7IiBkPSJNIDQyIDM3IEMgNDIgMzkuNzYx
            NzE5IDM5Ljc2MTcxOSA0MiAzNyA0MiBMIDExIDQyIEMgOC4yMzgyODEgNDIgNiAzOS43NjE3MTkgNiAzNyBMIDYgMTEgQyA2IDguMjM
            4MjgxIDguMjM4MjgxIDYgMTEgNiBMIDM3IDYgQyAzOS43NjE3MTkgNiA0MiA4LjIzODI4MSA0MiAxMSBaICI+PC9wYXRoPjxwYXRoIH
            N0eWxlPSIgZmlsbDojRkZGRkZGOyIgZD0iTSAzNC4zNjcxODggMjUgTCAzMSAyNSBMIDMxIDM4IEwgMjYgMzggTCAyNiAyNSBMIDIzI
            DI1IEwgMjMgMjEgTCAyNiAyMSBMIDI2IDE4LjU4OTg0NCBDIDI2LjAwMzkwNiAxNS4wODIwMzEgMjcuNDYwOTM4IDEzIDMxLjU5Mzc1
            IDEzIEwgMzUgMTMgTCAzNSAxNyBMIDMyLjcxNDg0NCAxNyBDIDMxLjEwNTQ2OSAxNyAzMSAxNy42MDE1NjMgMzEgMTguNzIyNjU2IEw
            gMzEgMjEgTCAzNSAyMSBaICI+PC9wYXRoPjwvZz48L3N2Zz4=" alt="Facebook" title="Facebook">
        </a>
        <a href="https://www.instagram.com/tima_prisyazhnyuk/?hl=ru" target="_blank">
            <img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHg9IjBweCIgeT0i
            MHB4IgogICAgIHdpZHRoPSI1MCIgaGVpZ2h0PSI1MCIKICAgICB2aWV3Qm94PSIwIDAgNDggNDgiCiAgICAgc3R5bGU9ImZpbGw6IzAw
            MDAwMDsiPjxnIGlkPSJzdXJmYWNlMSI+PHBhdGggc3R5bGU9IiBmaWxsOiNGRkNDODA7IiBkPSJNIDYgMTggTCA2IDM3IEMgNiAzOS43N
            jE3MTkgOC4yMzgyODEgNDIgMTEgNDIgTCAzNyA0MiBDIDM5Ljc2MTcxOSA0MiA0MiAzOS43NjE3MTkgNDIgMzcgTCA0MiAxOCBaICI+PC
            9wYXRoPjxwYXRoIHN0eWxlPSIgZmlsbDojNzk1NTQ4OyIgZD0iTSA0MiAxOCBMIDQyIDExIEMgNDIgOC4yMzgyODEgMzkuNzYxNzE5ID
            YgMzcgNiBMIDExIDYgQyA4LjIzODI4MSA2IDYgOC4yMzgyODEgNiAxMSBMIDYgMTggWiAiPjwvcGF0aD48cGF0aCBzdHlsZT0iIGZpbGw
            6IzM3NDc0RjsiIGQ9Ik0gMzIgMjUgQyAzMiAyOS40MTc5NjkgMjguNDE3OTY5IDMzIDI0IDMzIEMgMTkuNTgyMDMxIDMzIDE2IDI5LjQx
            Nzk2OSAxNiAyNSBDIDE2IDIwLjU4MjAzMSAxOS41ODIwMzEgMTcgMjQgMTcgQyAyOC40MTc5NjkgMTcgMzIgMjAuNTgyMDMxIDMyIDI1IF
            ogIj48L3BhdGg+PHBhdGggc3R5bGU9IiBmaWxsOiNGRkYzRTA7IiBkPSJNIDI0IDM0IEMgMTkuMDM5MDYzIDM0IDE1IDI5Ljk2NDg0NCA
            xNSAyNSBDIDE1IDIwLjAzOTA2MyAxOS4wMzkwNjMgMTYgMjQgMTYgQyAyOC45NjQ4NDQgMTYgMzMgMjAuMDM5MDYzIDMzIDI1IEMgMzMg
            MjkuOTY0ODQ0IDI4Ljk2NDg0NCAzNCAyNCAzNCBaIE0gMjQgMTggQyAyMC4xNDA2MjUgMTggMTcgMjEuMTQwNjI1IDE3IDI1IEMgMTcgMj
            guODU5Mzc1IDIwLjE0MDYyNSAzMiAyNCAzMiBDIDI3Ljg1OTM3NSAzMiAzMSAyOC44NTkzNzUgMzEgMjUgQyAzMSAyMS4xNDA2MjUgMjcu
            ODU5Mzc1IDE4IDI0IDE4IFogIj48L3BhdGg+PHBhdGggc3R5bGU9IiBmaWxsOiM1NDZFN0E7IiBkPSJNIDI5IDI1IEMgMjkgMjcuNzYxNz
            E5IDI2Ljc2MTcxOSAzMCAyNCAzMCBDIDIxLjIzODI4MSAzMCAxOSAyNy43NjE3MTkgMTkgMjUgQyAxOSAyMi4yMzgyODEgMjEuMjM4Mjgx
            IDIwIDI0IDIwIEMgMjYuNzYxNzE5IDIwIDI5IDIyLjIzODI4MSAyOSAyNSBaICI+PC9wYXRoPjxwYXRoIHN0eWxlPSIgZmlsbDojQkJERU
            ZCOyIgZD0iTSAyNCAyMyBDIDI0IDI0LjEwNTQ2OSAyMy4xMDU0NjkgMjUgMjIgMjUgQyAyMC44OTQ1MzEgMjUgMjAgMjQuMTA1NDY5IDIw
            IDIzIEMgMjAgMjEuODk0NTMxIDIwLjg5NDUzMSAyMSAyMiAyMSBDIDIzLjEwNTQ2OSAyMSAyNCAyMS44OTQ1MzEgMjQgMjMgWiAiPjwvcG
            F0aD48cGF0aCBzdHlsZT0iIGZpbGw6I0Y0NDMzNjsiIGQ9Ik0gOCA3LjAyMzQzOCBMIDggMTggTCAxMCAxOCBMIDEwIDYuMTAxNTYzIEMg
            OS4yNTc4MTMgNi4yNTM5MDYgOC41ODU5MzggNi41ODIwMzEgOCA3LjAyMzQzOCBaICI+PC9wYXRoPjxwYXRoIHN0eWxlPSIgZmlsbDojRk
            ZFQjNCOyIgZD0iTSAxMSA2IEMgMTAuNjU2MjUgNiAxMC4zMjQyMTkgNi4wMzUxNTYgMTAgNi4xMDE1NjMgTCAxMCAxOCBMIDEyIDE4IEwg
            MTIgNiBaICI+PC9wYXRoPjxwYXRoIHN0eWxlPSIgZmlsbDojOEJDMzRBOyIgZD0iTSAxMiA2IEwgMTQgNiBMIDE0IDE4IEwgMTIgMTggWiA
            iPjwvcGF0aD48cGF0aCBzdHlsZT0iIGZpbGw6IzIxOTZGMzsiIGQ9Ik0gMTQgNiBMIDE2IDYgTCAxNiAxOCBMIDE0IDE4IFogIj48L3BhdG
            g+PHBhdGggc3R5bGU9IiBmaWxsOiMzRTI3MjM7IiBkPSJNIDMyIDkgTCAzOCA5IEwgMzggMTUgTCAzMiAxNSBaICI+PC9wYXRoPjxwYXRoI
            HN0eWxlPSIgZmlsbDojM0UyNzIzOyIgZD0iTSAxNiAxNy41IEMgMTYgMTguMzI4MTI1IDE1LjMyODEyNSAxOSAxNC41IDE5IEwgOS41IDE5I
            EMgOC42NzE4NzUgMTkgOCAxOC4zMjgxMjUgOCAxNy41IEMgOCAxNi42NzE4NzUgOC42NzE4NzUgMTYgOS41IDE2IEwgMTQuNSAxNiBDIDE1L
            jMyODEyNSAxNiAxNiAxNi42NzE4NzUgMTYgMTcuNSBaICI+PC9wYXRoPjwvZz48L3N2Zz4=" alt="Instagram" title="Instagram">
        </a>
        <a href="https://github.com/TimofiyPrisyazhnyuk" target="_blank">
            <img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHg9IjBweCIgeT0i
            MHB4IgogICAgIHdpZHRoPSI1MCIgaGVpZ2h0PSI1MCIKICAgICB2aWV3Qm94PSIwIDAgNjQgNjQiCiAgICAgc3R5bGU9ImVuYWJsZS1i
            YWNrZ3JvdW5kOm5ldyAwIDAgNjQgNjQ7O2ZpbGw6IzAwMDAwMDsiPjxsaW5lYXJHcmFkaWVudCBpZD0iU1ZHSURfMV9fNTI1MzkiIGdy
            YWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIiB4MT0iMzAuOTk4OSIgeTE9IjE2IiB4Mj0iMzAuOTk4OSIgeTI9IjU1LjM0MjIiIHNw
            cmVhZE1ldGhvZD0icmVmbGVjdCI+CTxzdG9wIG9mZnNldD0iMCIgc3R5bGU9InN0b3AtY29sb3I6IzZEQzdGRiI+PC9zdG9wPgk8c3Rv
            cCBvZmZzZXQ9IjEiIHN0eWxlPSJzdG9wLWNvbG9yOiNFNkFCRkYiPjwvc3RvcD48L2xpbmVhckdyYWRpZW50PjxwYXRoIHN0eWxlPSJm
            aWxsOnVybCgjU1ZHSURfMV9fNTI1MzkpOyIgZD0iTTI1LjAwOCw1Ni4wMDdjLTAuMDAzLTAuMzY4LTAuMDA2LTEuOTYyLTAuMDA5LTMu
            NDU0bC0wLjAwMy0xLjU1ICBjLTYuNzI5LDAuOTE1LTguMzU4LTMuNzgtOC4zNzYtMy44M2MtMC45MzQtMi4zNjgtMi4yMTEtMy4wNDUt
            Mi4yNjYtMy4wNzNsLTAuMTI0LTAuMDcyYy0wLjQ2My0wLjMxNi0xLjY5MS0xLjE1Ny0xLjM0Mi0yLjI2MyAgYzAuMzE1LTAuOTk3LDEuN
            TM2LTEuMSwyLjA5MS0xLjA4MmMzLjA3NCwwLjIxNSw0LjYzLDIuOTc4LDQuNjk0LDMuMDk1YzEuNTY5LDIuNjg5LDMuOTY0LDIuNDExLD
            UuNTA5LDEuODQ0ICBjMC4xNDQtMC42ODgsMC4zNjctMS4zMiwwLjY1OS0xLjg3OEMyMC44ODUsNDIuODY1LDE1LjI3LDQwLjIyOSwxNS4
            yNywzMC42NGMwLTIuNjMzLDAuODItNC45NiwyLjQ0MS02LjkyOSAgYy0wLjM2Mi0xLjIwNi0wLjc3NC0zLjY2NiwwLjQ0Ni02Ljc2NWww
            LjE3NC0wLjQ0MmwwLjQ1Mi0wLjE0NGMwLjQxNi0wLjEzNywyLjY4OC0wLjYyNCw3LjM1OSwyLjQzMyAgYzEuOTI4LTAuNDk0LDMuOTY5L
            TAuNzQ5LDYuMDc0LTAuNzU5YzIuMTE1LDAuMDEsNC4xNTgsMC4yNjUsNi4wOSwwLjc1OWM0LjY2Ny0zLjA1OCw2LjkzNC0yLjU2NSw3Lj
            M1MS0yLjQzM2wwLjQ1MSwwLjE0NSAgbDAuMTc0LDAuNDRjMS4yMjUsMy4wOTgsMC44MTMsNS41NTksMC40NTEsNi43NjZjMS42MTgsMS4
            5NjMsMi40MzgsNC4yOTEsMi40MzgsNi45MjljMCw5LjU5MS01LjYyMSwxMi4yMTktMTAuNTg4LDEzLjA4NyAgYzAuNTYzLDEuMDY1LDAuO
            DY4LDIuNDAyLDAuODY4LDMuODc4YzAsMS42ODMtMC4wMDcsNy4yMDQtMC4wMTUsOC40MDJsLTItMC4wMTRjMC4wMDgtMS4xOTYsMC4wMT
            UtNi43MDgsMC4wMTUtOC4zODkgIGMwLTIuNDQyLTAuOTQzLTMuNTIyLTEuMzUtMy44NzRsLTEuNzMtMS40OTdsMi4yNzQtMC4yNTNjNS4y
            MDUtMC41NzgsMTAuNTI1LTIuMzc5LDEwLjUyNS0xMS4zNDFjMC0yLjMzLTAuNzc3LTQuMzYxLTIuMzEtNi4wMzYgIGwtMC40My0wLjQ2OW
            wwLjI0Mi0wLjU4N2MwLjE2Ni0wLjQwMSwwLjg5NC0yLjQ0Mi0wLjA0My01LjI5MWMtMC43NTgsMC4wNDUtMi41NjgsMC40MDItNS41ODQs
            Mi40NDdsLTAuMzg0LDAuMjU5bC0wLjQ0NS0wLjEyMyAgYy0xLjg2My0wLjUxOC0zLjkzOC0wLjc5Ni02LjAwMS0wLjgwNmMtMi4wNTIsMC
            4wMS00LjEyNCwwLjI4OC01Ljk4NCwwLjgwNmwtMC40NDUsMC4xMjNsLTAuMzgzLTAuMjU5ICBjLTMuMDE5LTIuMDQ0LTQuODMzLTIuNDA
            0LTUuNTk0LTIuNDQ5Yy0wLjkzNSwyLjg1MS0wLjIwNiw0Ljg5Mi0wLjA0LDUuMjkzbDAuMjQyLDAuNTg3bC0wLjQyOSwwLjQ2OSAgYy0
            xLjUzNiwxLjY4MS0yLjMxNCwzLjcxMi0yLjMxNCw2LjAzNmMwLDguOTU4LDUuMzEsMTAuNzcsMTAuNTA0LDExLjM2MWwyLjI1MiwwLjI
            1NmwtMS43MDgsMS40OSAgYy0wLjM3MiwwLjMyNS0xLjAzLDEuMTEyLTEuMjU0LDIuNzI3bC0wLjA3NSwwLjU0OWwtMC41MDYsMC4yMjd
            jLTEuMzIxLDAuNTkyLTUuODM5LDIuMTYyLTguNTQ4LTIuNDg1ICBjLTAuMDE1LTAuMDI1LTAuNTQ0LTAuOTQ1LTEuNTAyLTEuNTU3Yz
            AuNjQ2LDAuNjM5LDEuNDMzLDEuNjczLDIuMDY4LDMuMjg3YzAuMDY2LDAuMTksMS4zNTcsMy42MjIsNy4yOCwyLjMzOWwxLjIwNi0wL
            jI2MiAgbDAuMDEyLDMuOTc4YzAuMDAzLDEuNDg3LDAuMDA2LDMuMDc2LDAuMDA5LDMuNDQ0TDI1LjAwOCw1Ni4wMDd6Ij48L3BhdGg+
            PGxpbmVhckdyYWRpZW50IGlkPSJTVkdJRF8yX181MjUzOSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiIHgxPSIzMiIgeTE
            9IjUiIHgyPSIzMiIgeTI9IjU5LjE2NjkiIHNwcmVhZE1ldGhvZD0icmVmbGVjdCI+CTxzdG9wIG9mZnNldD0iMCIgc3R5bGU9InN0b3
            AtY29sb3I6IzFBNkRGRiI+PC9zdG9wPgk8c3RvcCBvZmZzZXQ9IjEiIHN0eWxlPSJzdG9wLWNvbG9yOiNDODIyRkYiPjwvc3RvcD48L
            2xpbmVhckdyYWRpZW50PjxwYXRoIHN0eWxlPSJmaWxsOnVybCgjU1ZHSURfMl9fNTI1MzkpOyIgZD0iTTMyLDU4QzE3LjY2Myw1OCw2
            LDQ2LjMzNyw2LDMyUzE3LjY2Myw2LDMyLDZzMjYsMTEuNjYzLDI2LDI2UzQ2LjMzNyw1OCwzMiw1OHogTTMyLDggIEMxOC43NjcsOCw
            4LDE4Ljc2Nyw4LDMyczEwLjc2NywyNCwyNCwyNHMyNC0xMC43NjcsMjQtMjRTNDUuMjMzLDgsMzIsOHoiPjwvcGF0aD48L3N2Zz4="
                 alt="GitHub" title="GitHub">
        </a>
    </div>
    <div id="rights">
        <small>Все права защищены &copy; <?php echo date('Y'); ?></small>
    </div>
</footer>